name: Terraform Apply on main

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'

jobs:
  terraform-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5

      - name: Create expected files from secrets
        run: |
          echo '${{ secrets.YC_SA_JSON_KEY }}' > .authorized_key.json
          mkdir -p k8s/CSI
          echo '${{ secrets.YC_CSI_SA_JSON_KEY }}' > k8s/CSI/.authorized_key.json

      - name: Create backend config
        run: |
          cat > backend.tfbackend << EOF
          bucket = "${{ secrets.BUCKET_NAME }}"
          access_key = "${{ secrets.ACCESS_KEY }}"
          secret_key = "${{ secrets.SECRET_KEY }}"
          key = "${{ secrets.KEY }}"
          endpoint = "${{ secrets.ENDPOINT }}"
          region = "${{ secrets.REGION }}"
          skip_requesting_account_id = true
          skip_region_validation = true
          skip_credentials_validation = true
          EOF

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init -backend-config=../backend.tfbackend

      - name: Terraform Plan
        working-directory: ./infra
        id: plan
        env:
          TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
          TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
          TF_VAR_username: ${{ secrets.YC_USERNAME }}
          TF_VAR_ssh_public_key: ${{ secrets.YC_SSH_PUBLIC_KEY }}
        run: |
          terraform plan -detailed-exitcode -no-color -out=tfplan || exit_code=$?
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
        continue-on-error: true

      # ВОТ ЭТОТ ШАГ НУЖНО ДОБАВИТЬ
      - name: Terraform Apply
        working-directory: ./infra
        if: steps.plan.outputs.exit_code == 2  # 2 = есть изменения
        env:
          TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
          TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
          TF_VAR_username: ${{ secrets.YC_USERNAME }}
          TF_VAR_ssh_public_key: ${{ secrets.YC_SSH_PUBLIC_KEY }}
        run: terraform apply -auto-approve tfplan

      - name: No changes
        if: steps.plan.outputs.exit_code == 0
        run: echo "No changes to apply"

      - name: Plan failed
        if: steps.plan.outputs.exit_code == 1
        run: exit 1